version: '2'
services:
  wordpress:
    container_name: my-other-wordpress-app
    image: wordpress
    ports: 
      - "80:80"  
    links:
      - "mysql:mysql"
  mysql:
    container_name: my-other-wordpress-database
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"