apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: wpfrontend
  name: wpfrontend
  namespace: kube-system
spec: 
  ports:
    - port: 80
  selector: 
    name: wordpress
  type: LoadBalancer
